version: '3'
services:
  portfolio:
    image: faisalmaliik/portfolio:latest
    container_name: portfolio
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    expose:
      - "80" 
      - "443"
    restart: always

  flix:
    image: faisalmaliik/flix:latest
    container_name: flix
    environment:
      - PORT=3000
    expose:
      - "3000"
    restart: always
