version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html
    depends_on:
      - portfolio
      - flix

  portfolio:
    image: faisalmaliik/portfolio:latest
    container_name: portfolio
    volumes:
      - /var/www/portfolio:/usr/share/nginx/html
    expose:
      - "80"

  flix:
    image: faisalmaliik/flix:latest
    container_name: flix
    environment:
      - PORT=3000
    expose:
      - "3000"
