version: '3'
services:
  load_balancer:
    image: nginx:alpine
    container_name: load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - portfolio
      - flix
    restart: always

  portfolio:
    image: faisalmaliik/portfolio:latest
    container_name: portfolio
    expose:
      - "80"
    restart: always

  flix:
    image: faisalmaliik/flix:latest
    container_name: flix
    environment:
      - PORT=3000
    expose:
      - "3000"
    restart: always
